version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      - image: postgres:9.6.2
      - image: nats
    working_directory: /go/src/github.com/ernestio/service-store
    steps:
      - checkout
      - run: make dev-deps
      - run: make lint
      - run:
          name: unit tests
          command: make test
          environment:
            NATS_URI:  nats://127.0.0.1:4222
            NATS_URI_TEST:  nats://127.0.0.1:4222
      - run:
          name: install docker compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > docker-compose
            sudo chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin/docker-compose
      - run:
          name: install ruby
          command: |
            set -x
            sudo apt update
            sudo apt install ruby2.2 gem
      - run: git clone git@github.com:ernestio/toolset.git
      - run: cd toolset/ernestci/ && gem install bundler && bundle install
      - run:
          name: integration tests
          command: ruby ernestci/run.rb .ernest-ci
          environment:
            NATS_URI:  nats://127.0.0.1:4222
            NATS_URI_TEST:  nats://127.0.0.1:4222
            CURRENT_INSTANCE: http://127.0.0.1:80/
            JWT_SECRET: test
            ERNEST_LOG_FILE: '/tmp/ernest.log'
            ERNEST_CRYPTO_KEY: mMYlPIvI11z20H1BnBmB223355667788
